module.exports = {
    "proveedores": [
        'idproveedor',
        'nombre_contacto',
        'cargo_contacto',
        'email_contacto',
        'direccion',
        'ciudad',
        'pais',
        'telefono',
        'url',
        'descripcion',
        'status',
        'codigo',
        'tipo_licencia',
        'ruc',
        'fax',
        'dv',
        'fecha'
    ],
    "activos": [
        'idactivo',
        'tipoitem',
        'codigo',
        'nombre',
        'marca',
        'descripcion',
        'fecha'
    ],
    "medidas": [
        'idmedida',
        'abreviatura',
        'nombre',
        'descripcion',
        'fecha'        
    ],
    "requisiciones": [
        'idrequisicion',
        'idusuario',
        'numero_requisicion',
        'fecha',
        'descripcion',
        'cotizacion1',
        'cotizacion2',
        'cotizacion3',
        'idverificador',
        'tipo',
        'codigo_presupuestario',
        'codigo_financiero',
        'fondo'
    ],
    "ordenes": [
        'idorden',
        'idrequisicion',
        'idproveedor',
        'numero',
        'fecha',
        'status',
        'lugar_entrega',
        'codigo_presupuestario',
        'codigo_financiero',
        'fianza_cumplimiento',
        'subtotal',
        'descuento',
        'itbm',
        'total',
        'observaciones'
    ]
};
